store:
    resource: "@StoreBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AdminBundle/Controller/'
    type: annotation

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
