# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AdminBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.product_image_uploader:
        class: AdminBundle\Services\FileUploader
        arguments: ['%products_images_directory%']
    repo.promotions:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - \AdminBundle\Entity\Promotion
    promotion_manager:
        class: AdminBundle\Services\PromotionManager
        arguments: ['@repo.promotions']
    app.price_calculator:
        class: AdminBundle\Services\PriceCalculator
        arguments: ['@promotion_manager']