<?php

namespace AdminBundle\Repository;


use AdminBundle\Entity\Category;
use AdminBundle\Entity\User;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    /**
     * return products for admin
     *
     * @return QueryBuilder
     */
    public function getAllProductsAdmin()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select(['p', 'pc', 'pfe'])
            ->from('AdminBundle:Product', 'p')
            ->leftJoin('p.categories', 'pc')
            ->leftJoin('p.featured', 'pfe')
            ->where($qb->expr()->neq('p.deleted', 1));

        return $qb;
    }

    /**
     * return products for admin
     *
     * @param string $searchWords
     * @return QueryBuilder
     */
    public function searchProductsAdmin($searchWords)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select('p', 'pc')
            ->from('AdminBundle:Product', 'p')
            ->leftJoin('p.categories', 'pc');

        $searchWords = explode(' ', $searchWords);
        $cqbORX = [];

        foreach ($searchWords as $searchWord) {
            $cqbORX[] = $qb->expr()->like('p.name', $qb->expr()->literal('%' . $searchWord . '%'));
            $cqbORX[] = $qb->expr()->like('p.description', $qb->expr()->literal('%' . $searchWord . '%'));
        }

        $qb->andWhere(call_user_func_array([$qb->expr(), "orx"], $cqbORX));

        return $qb;
    }

    /**
     * @param Category $category
     * @return QueryBuilder
     */
    public function findByCategoryQB($id)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select(['p', 'pfe'])
            ->from('AdminBundle:Product', 'p')
            ->innerJoin('p.categories', 'ca')
            ->leftJoin('p.featured', 'pfe')
            ->where('ca = :id')
            ->andWhere('p.quantity > 0')
            ->andWhere($qb->expr()->neq('p.deleted', 1))
            ->setParameter('id', $id);

        return $qb;
    }

    /**
     * @param int $quantity
     * @param User $user
     * @return array
     */
    public function getFeatured($quantity = 1)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select(['p', 'pfe'])
            ->from('AdminBundle:Product', 'p')
            ->innerJoin('p.featured', 'pfe')
            ->where('p.quantity <> 0')
            ->andWhere($qb->expr()->neq('p.deleted', 1))
            ->setMaxResults($quantity)
            ->addOrderBy('pfe.productOrder', 'DESC');

        return $qb->getQuery()->getResult();
    }
}
